# Generated by Django 5.0.6 on 2024-07-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_name', models.CharField(default='', max_length=50)),
                ('Trainer_name', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('duration', models.CharField(default=30)),
                ('fee', models.CharField(default=5000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('course_name', models.CharField(default='', max_length=50)),
                ('date_of_visit', models.DateField()),
                ('source', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=50)),
                ('mode', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='paymets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=50)),
                ('Batche_id', models.CharField(default='', max_length=50)),
                ('Amount', models.CharField(default='')),
                ('date_of_payment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('Batche_id', models.CharField(default='', max_length=50)),
                ('course_name', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('fee', models.CharField(default=5000)),
                ('paid', models.CharField(default='')),
                ('pending', models.CharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=10, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('course_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=10, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
