# Generated by Django 5.0.6 on 2024-07-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymets',
            old_name='student_name',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='batches',
            name='Batch_id',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='leads',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='batches',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
