# Generated by Django 5.0.6 on 2024-07-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_rename_student_name_paymets_student_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paymets',
            new_name='payments',
        ),
        migrations.AlterField(
            model_name='students',
            name='Batche_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
