# Generated by Django 5.0.6 on 2024-07-02 09:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_rename_course_name_leads_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='leads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=10), size=None),
        ),
    ]
