# Generated by Django 5.0.6 on 2024-07-02 10:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_alter_batches_leads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batches',
            old_name='Trainer_name',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='batches',
            old_name='course_name',
            new_name='trainer_id',
        ),
        migrations.AlterField(
            model_name='batches',
            name='leads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), size=None),
        ),
    ]
