# Generated by Django 5.0.6 on 2024-07-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_rename_trainer_name_batches_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='Batche_id',
            new_name='Batch_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Batche_id',
            new_name='Batch_id',
        ),
    ]
